### PR TITLE
Add Design folder with .gitkeep

### PR DESCRIPTION
**Pull request by sanidhaya**

### CODE REVIEW

**Review by s1ashd0t — APPROVED** [review]

**Comment by zeshengchen** [comment]
If the pull request is ready for peer review, please invite all group members by selecting them in "Reviewers" on right-top conner of this page.

**Review by lukebushur — APPROVED** [review]
Looks good!

**Review by ayushdh96 — APPROVED** [review]
Looks good to me.

**Review by DRASHHTIPATEL — APPROVED** [review]
Went through it. Looks good!

**Comment by zeshengchen** [comment]
@sanidhaya please complete this pull request soon!

**Pull request merged**
