### PR TITLE
Initial Trained VGG Autoencoder

### PR DESCRIPTION
**Pull request by lukebushur**
The code is finished now.

The code gets data from Librispeech and preprocesses it. The preprocessing builds upon Ayush's preprocessing techniques and performs the following:
- Loops through all the audio files and loads them into memory
- Creates noisy audio so that we can have noisy audio for input and clean audio for expected output for training
- Divides the audio into chunks of just over 1 second long (so that the shape of the spectrograms are each (128, 32)
- Converts the chunks into spectrograms and stores them into a numpy array
- repeats the lowest value 3 times to get 3 channels (since the model expects an input shape of (128, 32, 3)
- Splits the data into train and test data (I do not actually perform testing, as that is another group member's job)
- Normalizes the spectrogram values so that they are in the range of 0 to 1.

Then, the model is compiled and trained on all the data. The saved model is included in the pull request

In the future, we might consider performing different data augmentation techniques, such as blending clean audio with predefined environmental noises (traffic, alarms, etc.). One of the reasons the model might be performing so well is that adding noise involves simply adding a random value to each value in the audio. @ayushdh96 could you look into doing this after the midterm presentation?

Alternatively (and more likely), the model might be performing well because I am doing something wrong (e.g., mixing train and test data). Please let me know if you notice anything to this effect.

Uploaded 3 files:
- model_training_vgg_autoencoder.ipynb
  - Jupyter notebook with the code
- model_training_vgg_autoencoder.py
  - Python file with the code
- trained_model.keras
  - the trained model saved as a keras file

OLD DESCRIPTION:
Includes my model trained on 149 audio samples from Librispeech. This was done just to test that I could train the model with preprocessing from Ayush.

note: Please do not merge this pull request until I say it is ready - I wanted to share the code so that others could reference my workflow. Once it is ready, I will provide more information on it with an updated description.

### CODE REVIEW

**Comment by sanidhaya** [comment]
Good work, Just let @DRASHHTIPATEL  and @s1ashd0t know once you are done

**Comment by lukebushur** [comment]
@sanidhaya @ayushdh96 @DRASHHTIPATEL @s1ashd0t just letting you know the pull request is ready now.

**Review by DRASHHTIPATEL — APPROVED** [review]
Looks great!

**Review by s1ashd0t — APPROVED** [review]
looks good. I will try to eval

**Review by ayushdh96 — APPROVED** [review]
Model looks complete now.

**Comment by ayushdh96** [comment]
Sounds like a good plan. I will look into that post presentation. By adding more of the audio types for preprocesing.

**Comment by zeshengchen** [comment]
@sanidhaya Next time before you merged the pull request, please approve it first! 

Moreover, it would be better to let the group member who generated the pull request to complete it.

**Pull request merged**
