### PR TITLE
This is general pre processing code

### PR DESCRIPTION
**Pull request by ayushdh96**
Hello guys,

I was just thinking to create a basic general pre processing for the models, which the team members training the model can initially use.
Just a basic one, not specified to the task but basic audio and general noise.
You don't need to use this, but keeping this here just in case someone wants to use this for quick pre processing and seeing if the models is taking preprocessing in the format.
So that post this then you can move ahead with specialized pre processing.

### CODE REVIEW

**Review by s1ashd0t — APPROVED** [review]
Nice! I think i could use it.

**Review by lukebushur — APPROVED** [review]
Looks good--thanks for the utility!

**Review by sanidhaya — APPROVED** [review]

**Comment by DRASHHTIPATEL** [comment]
Looks good!

**Review by DRASHHTIPATEL — APPROVED** [review]
Great generalisation!

**Pull request merged**
