### PR TITLE
added Deployment file

### PR DESCRIPTION
**Pull request by sanidhaya**
just added a main.py file

### CODE REVIEW

**Comment by zeshengchen** [comment]
If this pull request is ready for peer review, please invite all other group members to review it!

**Comment by zeshengchen** [comment]
What is the status of this pull request?

**Comment by sanidhaya** [comment]
Good evening @zeshengchen sir, 

This is the deployment branch, we will merge it at the very last.

**Review by s1ashd0t — APPROVED** [review]
code approved!

**Review by ayushdh96 — APPROVED** [review]
Looks good to me. Great work.

**Review by DRASHHTIPATEL — APPROVED** [review]
Really good advancements!!

**Pull request merged**
