### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by DRASHHTIPATEL**
EFFICIENTNET BASED MODEL

I tried using an EfficientNet-based autoencoder model to tackle audio denoising. The idea was to convert audio files into Mel spectrograms, add some noise, and then train the model to learn how to clean them up by comparing noisy and clean versions.  

Required packages include TensorFlow, librosa, soundfile, and numpy.

### CODE REVIEW

**Comment by zeshengchen** [comment]
If the pull request is ready, please put other group members into the list of reviewers.

**Comment by DRASHHTIPATEL** [comment]
@zeshengchen Good Morning Professor! I have added everyone as reviewers . Thank you so much.

**Review by sanidhaya — COMMENTED** [review]
Make sure it is compatible with different models

**Review by ayushdh96 — APPROVED** [review]

**Comment by ayushdh96** [comment]
Looks good. Greart idea to divulgue in more models to find the optimal one.

**Review by lukebushur — APPROVED** [review]
As long as it works, it looks good!

**Review by s1ashd0t — APPROVED** [review]
merging approved

**Review by sanidhaya — APPROVED** [review]

**Pull request merged**
