### PR TITLE
Utilities for U-Net Model

### PR DESCRIPTION
**Pull request by lukebushur**
In the code, you will find some utilities to make using my U-Net model easier
- `denoise_audio` has dependencies on previous user-defined functions in the code. It will perform speech enhancement without phase information, instead opting for griffinlim to translate a linear spectrogram into a waveform. The results are a bit echoey, leading to the next function
- `denoise_audio_with_phase` has dependencies on previous user-defined functions in the code. It will perform speech enhancement using phase information from the input file, leading to less echoey results.
- `standalone_denoise_audio_with_phase` does not have any dependencies on previous user-defined functions in the code. It performs speech enhancement using phase information from the input file.

Feel free to use these utilities when using my model and when deploying. Please let me know if you have any feedback.

### CODE REVIEW

**Review by sanidhaya — APPROVED** [review]
works well

**Review by ayushdh96 — APPROVED** [review]
Great work to add these files on top of previous one for smooth functioning.

**Review by s1ashd0t — APPROVED** [review]
Nice! I ran the eval again on U-net 3 with a bigger dataset the resulting metrics were around the same.

**Review by DRASHHTIPATEL — APPROVED** [review]
great work!

**Pull request merged**
