### PR TITLE
added elements for pretrained model

### PR DESCRIPTION
**Pull request by sanidhaya**
### Go to deployment folder
**install the required libraries with** `pip install -r requirements.txt`
**and start the backend with** `uvicorn main:app --reload --host 0.0.0.0 --port 8000`

On a separate terminal

### Go to audio-frontend folder
**install the required libraries with** `npm i`
**start the frontend with** `npm start`

## **Try running it and I would appreciate the criticism**

### CODE REVIEW

**Review by zeshengchen — APPROVED** [review]

**Review by lukebushur — COMMENTED** [review]
I will try running it tonight.

**Review by DRASHHTIPATEL — APPROVED** [review]
Amazing! Will look into it super soon.

**Review by ayushdh96 — APPROVED** [review]
Perfect. Looks good to me.

**Review by lukebushur — APPROVED** [review]
Front-end looks great!

**Comment by zeshengchen** [comment]
@s1ashd0t Please peer review this pull request and other pull requests ASAP. For example, this pull request has been there fore 4 days, but you have not provided any feedback yet.

**Review by s1ashd0t — APPROVED** [review]
@sanidhaya Sorry for the late review. 

I tried to run it on my machine the backend starts correctly, front-end too. but when i try to process something it shows internal server error.

**Comment by zeshengchen** [comment]
> @sanidhaya Sorry for the late review.
> 
> I tried to run it on my machine the backend starts correctly, front-end too. but when i try to process something it shows internal server error.

It would be much better that you can post a screenshot on the internal server error you got here.

**Comment by s1ashd0t** [comment]
> > @sanidhaya Sorry for the late review.
> > I tried to run it on my machine the backend starts correctly, front-end too. but when i try to process something it shows internal server error.
> 
> It would be much better that you can post a screenshot on the internal server error you got here.

Sure Professor,

Here it is: 

Screenshot 2024-12-06 181332

The error is: 
```
ERROR:main:Error processing audio: Couldn't find appropriate backend to handle uri <_io.BytesIO object at 0x000002B71052D580> and format None.
INFO:     127.0.0.1:50442 - "PUT /process-audio/?model=dns HTTP/1.1" 500 Internal Server Error

```

**Comment by sanidhaya** [comment]
Ill make sure to remove the internal servor error asap

**Pull request merged**
