### PR TITLE
added functionalities regarding listing to unprocessed and processed …

### PR DESCRIPTION
**Pull request by sanidhaya**
…audio at the same time and option for download.

### CODE REVIEW

**Review by lukebushur — APPROVED** [review]
Looks good!

**Review by ayushdh96 — APPROVED** [review]
Approach and the code, both looks good. keep up the good work,.

**Review by DRASHHTIPATEL — APPROVED** [review]
Looks pretty amazing! Kudos!

**Review by s1ashd0t — APPROVED** [review]
code reviewed. It looks good!

**Pull request merged**
