### PR TITLE
SEGAN FINE TUNED MODEL

### PR DESCRIPTION
**Pull request by DRASHHTIPATEL**
In this repository, I worked on fine-tuning the SEGAN (Speech Enhancement Generative Adversarial Network) model to improve its performance in audio denoising. The original model tended to amplify the noise, but after fine-tuning it with my custom dataset of noisy and clean audio, the model now successfully reduces noise while maintaining the quality of the audio.

To improve the model's performance, I fine-tuned the SEGAN model by training it on a custom dataset of noisy and clean audio pairs. The dataset consists of noisy audio as input and clean audio as the target output. During fine-tuning, the model learns to generate cleaner versions of the noisy input by minimizing the difference between the generated audio and the actual clean audio. Additionally, I used a discriminator to guide the generator by distinguishing between real (clean) and fake (generated) audio.

In a day or two , I plan to experiment with an updated set of noisy audio files, which were preprocessed by Ayush. This new dataset will allow me to further evaluate the model’s ability to denoise more challenging noisy inputs.

I have also included certain evaluation metrics which might be considered useful for this model in the doc file.

Looking forward to your reviews!

### CODE REVIEW

**Review by zeshengchen — APPROVED** [review]
It is a good idea to add the running results on SNR, MSE, PESQ into the Segan.docx file.

**Review by lukebushur — APPROVED** [review]
Looks good! Glad you were able to get a model working!

**Review by sanidhaya — APPROVED** [review]
Good work man

**Review by ayushdh96 — APPROVED** [review]
Great to see the model working like we wanted to. Thanks. Let me know if more changes are required for the pre processing of the model.

**Comment by s1ashd0t** [comment]
you have not included the model in here. I would not be able to run evaluation on it unless I finetune the model again

**Comment by DRASHHTIPATEL** [comment]
> you have not included the model in here. I would not be able to run evaluation on it unless I finetune the model again

I have uploaded the .h5 files . Kindly refer to those.

**Review by s1ashd0t — APPROVED** [review]
Thanks. I will evaluate it ASAP

**Pull request merged**
