### PR TITLE
Model Definition and Model File

### PR DESCRIPTION
**Pull request by lukebushur**
Created Jupyter notebook and an associated python file that defines a model for audio denoising.
- The model uses an encoder-decoder architecture. More specifically, it is an autoencoder
  - The encoder is a pre-trained model. Support exists for VGG16 and ResNet50. If we decide we want to use a different pre-trained model, I can add it. The input shape is `(224, 224, 3)`, but the first two dimensions can be changed depending on the size of the spectrogram.
  - The bottleneck stores the data from the encoder for use in the decoder.
  - The decoder uses the bottleneck's understanding to reconstruct the spectrogram.
- The model is saved in the updated_model.keras file. It can be loaded using `keras.saving.load_model("updated_model.keras")`
- Note: Due to the size of the model (almost 4 million trainable parameters), I am a little worried about how long training might take. If it does take too long, we might look towards a different approach (e.g., stepping away from a pre-trained model to define our own, smaller model or using a model already built for audio denoising from Hugging Face).

### CODE REVIEW

**Comment by lukebushur** [comment]
I would also like to say that, if you have any suggestions, I am open to any feedback you might have.

**Review by s1ashd0t — APPROVED** [review]
Code reviewed.

**Review by ayushdh96 — APPROVED** [review]
Hello Luke, this looks good to me. Hope you saw the Speechbrain pretrained model code as well that I had pushed.

**Review by DRASHHTIPATEL — APPROVED** [review]
Hi Luke , the model choice seems to be good. We may also experiment with the DEMUCS model if the time constraint serves as an issue at later stages . As of now , this is great.

**Comment by zeshengchen** [comment]
@sanidhaya please peer review this pull request soon!

**Comment by sanidhaya** [comment]
This is good work

**Review by sanidhaya — COMMENTED** [review]
code is good and good

**Pull request merged**
