### PR TITLE
added evaluation metrics

### PR DESCRIPTION
**Pull request by s1ashd0t**
generate performance report based on test files

### CODE REVIEW

**Review by sanidhaya — COMMENTED** [review]
Great work @s1ashd0t

**Review by DRASHHTIPATEL — APPROVED** [review]
Great start! Looking forward for some amazing outputs for our entire project in near future!

**Comment by zeshengchen** [comment]
> Great work @s1ashd0t

@sanidhaya Please approve the pull request by clicking "Approve" button!

**Review by lukebushur — APPROVED** [review]
Looks good! Just make sure that when performing evaluation on the VGG autoencoder model, the LibriSpeech audio fed into this model is 1.02 seconds long. That way, when you extract the spectrogram, the input shape is the same as what the model is expecting (128, 32, 3)

**Comment by ayushdh96** [comment]
Great work for evaluation

**Review by ayushdh96 — APPROVED** [review]

**Comment by s1ashd0t** [comment]
> Looks good! Just make sure that when performing evaluation on the VGG autoencoder model, the LibriSpeech audio fed into this model is 1.02 seconds long. That way, when you extract the spectrogram, the input shape is the same as what the model is expecting (128, 32, 3)

Thanks! I think It would have been easier if I was able import the needed functions/components directly from your code in a modular fashion instead of creating new ones. I'll look into it

**Pull request merged**
