### PR TITLE
updated evaluation for new models

### PR DESCRIPTION
**Pull request by s1ashd0t**
added a mini test dataset formed on pairs of clean and noisy audio files. it should load the model and perform evaluation and output the metrics. see attached notebook for example. 

Please let me know if you have any questions.

### CODE REVIEW

**Review by zeshengchen — APPROVED** [review]
BTW, SNR result seems very low.

**Review by ayushdh96 — COMMENTED** [review]
@s1ashd0t , just want to confirm is the evaluation for the luke's model?

**Comment by s1ashd0t** [comment]
> BTW, SNR result seems very low.

Professor, I will run the test again to verify these metrics on larger dataset. I am just confirming if this will be final version of the model

**Review by lukebushur — APPROVED** [review]
Looks good! Glad we got some metrics to show!

**Review by sanidhaya — APPROVED** [review]
@zeshengchen the metrics might be low, the models are working fine and we are trying to provide a great output.

**Review by ayushdh96 — APPROVED** [review]
@s1ashd0t , got it. The metrics looks good then. Great work.

**Review by DRASHHTIPATEL — APPROVED** [review]
well done.

**Pull request merged**
