### PR TITLE
Model eval - updated metrics

### PR DESCRIPTION
**Pull request by s1ashd0t**
These are all the metrics needed for the project. Since we are currently working with multiple models, will not be able to compute the for all of them. When we finalize the model, I will adjust the code accordingly before merging. 

Let me know if something is missing or not working.

The additional_features branch PR should also be ready for review by next day.

If anyone is having an issue feel free to reach-out as we are in the final stretch now.

### CODE REVIEW

**Review by lukebushur — APPROVED** [review]
Looks good!

**Review by ayushdh96 — APPROVED** [review]
Looks great. presq calaulation is a good approach.

**Review by sanidhaya — APPROVED** [review]
These metrics are enough. I don't think we need more metrics

**Review by DRASHHTIPATEL — APPROVED** [review]
Seems fine ! Good work!

**Pull request merged**
