### PR TITLE
Demucs Model

### PR DESCRIPTION
**Pull request by DRASHHTIPATEL**
Update on successful implementation of the pretrained Demucs model for audio source separation, splitting audio files into vocals, drums, bass, and other components. It supports both single-file and batch processing, utilizing a pretrained HTDemucs model for high-quality separation. The separated components are saved as individual .wav files in the specified output directory. I would also like to thank Anayat for helping me with the error. Would love to know if any of you have any suggestions

### CODE REVIEW

**Review by zeshengchen — APPROVED** [review]
I approve this pull request, but it is not a good idea to put the file under the root of the project!

**Review by ayushdh96 — APPROVED** [review]
Thank you Drashti for this model. The code looks good to me.

**Review by lukebushur — APPROVED** [review]
Looks good! Does this replace the previous DEMUCS model pull request?

**Review by sanidhaya — APPROVED** [review]
code looke good

**Review by s1ashd0t — APPROVED** [review]
code looks okay. hope you saved the model

**Pull request merged**
