### PR TITLE
Pre precessing final

### PR DESCRIPTION
**Pull request by ayushdh96**
Hello guys,

With this I conclude the pre processing of the audio.
Please read the read me file, in which I've explained the process, what needs to be done and what the code does.
Also, I've added the noise_train folder with all the audio files needed to augment the audio.

I've addressed the previous naming convention issue as well.

Changes in this pull request.
1. Preprocessiong_final.py file, which contain the final approach to pre processing with augmenting not the system noise but real time noise.
2. Readme_preprocessing_final - The readme file which will allow you to understand what the code does, how to make it run, and how to change parameters to your liking.
3. noise_train- noise folder of different type of noise we're using to augment in our code.

The dataset to be used for the clean audio was provided by Dr. Chen and has already been mentioned in the earlier push and is here [](https://github.com/Deep-Learning-CS/CourseProjectDeepLearning/blob/pre_precessing_final/mainfile/Dataset%20For%20Audio.docx)

I've tried to be as thorough in the readme file, but still if you've any concern kindly reach out to me.

fyi - I wanted to inform you that I mistakenly created a folder in the main branch. Although this did not affect our workflow in any way, I corrected the error by deleting the folder immediately. I just wanted to make sure you're aware of this, as it was an oversight on my part.

### CODE REVIEW

**Review by DRASHHTIPATEL — APPROVED** [review]
Superb!
Thank you for the detailed update and for providing a clear breakdown of the changes in this pull request. 
The addition of the noise_train folder is a thoughtful enhancement for augmenting real-time noise, which aligns well with the objectives.
Excited to model around with the newly included data!

**Review by zeshengchen — APPROVED** [review]

**Review by lukebushur — APPROVED** [review]
Looks good! Thanks for getting this done!

**Review by s1ashd0t — APPROVED** [review]
cool! I guess that wraps-up preprocessing

**Review by sanidhaya — APPROVED** [review]
good work @s1ashd0t

**Comment by ayushdh96** [comment]
Merged

**Pull request merged**
